"""empty message

Revision ID: 16fc6943e52c
Revises: 2d4e9890df5e
Create Date: 2021-11-18 14:09:10.440990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fc6943e52c'
down_revision = '2d4e9890df5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('orderId', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'orderId')
    # ### end Alembic commands ###
