"""empty message

Revision ID: 2d4e9890df5e
Revises: dad4e1cf1d9c
Create Date: 2021-11-17 20:09:56.502425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4e9890df5e'
down_revision = 'dad4e1cf1d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('imageURL', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'imageURL')
    # ### end Alembic commands ###
